name: Build Check

on:
  pull_request:
    branches: [ "development","main" ]

jobs:
  tests:
    if: github.event.pull_request.user.login != vars.DEVOPS_BOT_NAME
    name: Build Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
